defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/mae"
  mode: "min"
  save_last: True
  auto_insert_metric_name: True

early_stopping:
  monitor: "val/mae"
  patience: 35
  mode: "min"

model_summary:
  max_depth: 2