defaults:
  - _self_
  - hydra: default.yaml
  - paths: default.yaml

task_name: "calc_stats"

deeplake_dataset_path: /network/scratch/o/oussama.boussif/TSEumetsat/tsf_eumetsat-64_64
years: [2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]
save_path: /home/mila/o/oussama.boussif/TSF_context_Eumetsat/stats_multi.json