_target_: src.pl_modules.cross_vivit_bis_quantile_mask.CrossViViTQuantileMask_bis

name: cvm_bis_quantile_mask
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0016
  weight_decay: 0.05
  betas: [0.9, 0.95]

scheduler:
  _target_: src.optim.cosine_warmup.CosineWarmupScheduler
  _partial_: true
  warmup: 5
  max_iters: ${trainer.max_epochs}

model:
  _target_: src.models.cross_vivit_bis.RoCrossViViT_bis
  image_size: [64, 64]
  patch_size: [8, 8]
  use_rotary: True
  use_glu: True
  freq_type: lucidrains
  max_freq: 64
  use_self_attention: True
  num_mlp_heads: 9

  ctx_masking_ratio: 0 
  ts_masking_ratio: 0.15

  dim: 64
  depth: 4
  heads: 4
  mlp_ratio: 4
  ctx_channels: 8
  ts_channels: 16
  ts_length: 48
  out_dim: 1
  dim_head: 64
  dropout: 0.3
  
  decoder_dim: 128
  decoder_depth: 4
  decoder_heads: 6
  decoder_dim_head: 128

  time_coords_encoder:
    _target_: src.models.modules.positional_encoding.Cyclical_embedding
    frequencies: [12, 31, 24, 60]

metrics:
  train:
    rmse:
      _target_: torchmetrics.MeanSquaredError
      squared: False
    mae:
      _target_: torchmetrics.MeanAbsoluteError
    mape:
      _target_: torchmetrics.MeanAbsolutePercentageError
    
    aufec_low_2:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: low
      cutoff_mode: 2
    aufec_low_3:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: low
      cutoff_mode: 3
    aufec_low_4:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: low
      cutoff_mode: 4
    aufec_low_5:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: low
      cutoff_mode: 5

    aufec_high_2:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: high
      cutoff_mode: 2
    aufec_high_3:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: high
      cutoff_mode: 3
    aufec_high_4:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: high
      cutoff_mode: 4
    aufec_high_5:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: high
      cutoff_mode: 5
  val:
    rmse:
      _target_: torchmetrics.MeanSquaredError
      squared: False
    mae:
      _target_: torchmetrics.MeanAbsoluteError
    mape:
      _target_: torchmetrics.MeanAbsolutePercentageError
    
    aufec_low_2:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: low
      cutoff_mode: 2
    aufec_low_3:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: low
      cutoff_mode: 3
    aufec_low_4:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: low
      cutoff_mode: 4
    aufec_low_5:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: low
      cutoff_mode: 5

    aufec_high_2:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: high
      cutoff_mode: 2
    aufec_high_3:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: high
      cutoff_mode: 3
    aufec_high_4:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: high
      cutoff_mode: 4
    aufec_high_5:
      _target_: src.metrics.aufec.AUFEC
      dim: 1
      mode: high
      cutoff_mode: 5

monitor: val/rmse
use_dp: True
cutoff_epoch: 100000 # Set high value if you don't want to use quantile_masks
criterion:
    _target_: src.losses.quantile_loss.QuantileLossMulti